# Generated by Django 5.2.17 on 2026-09-21 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('blurb', models.CharField(blank=True, default='', max_length=120)),
                ('craft', models.CharField(choices=[('writing', 'Creative Writing'), ('photo', 'Photography'), ('sketch', 'Sketch / Art'), ('joke', 'Joke')], max_length=16)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_prompts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='topics.topic')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_topics',
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['parent', 'is_active'], name='topics_parent__714d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='usertopic',
            index=models.Index(fields=['user'], name='user_topics_user_id_ac5259_idx'),
        ),
        migrations.AddConstraint(
            model_name='usertopic',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='uniq_user_topic'),
        ),
    ]
