# Generated by Django 5.2.17 on 2026-09-16 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('category', models.CharField(choices=[('writing', 'Creative Writing'), ('photo', 'Photography'), ('sketch', 'Sketch / Art'), ('joke', 'Joke')], max_length=16)),
                ('text', models.CharField(max_length=240)),
                ('nudge', models.CharField(default='Five minutes is enough.', max_length=120)),
                ('source', models.CharField(default='openai', max_length=16)),
                ('is_published', models.BooleanField(default=False, help_text='Human-reviewed and live.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompts',
                'ordering': ['-date'],
            },
        ),
    ]
