# Generated by Django 5.2.17 on 2026-09-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='topics.topic'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['date', 'is_published'], name='prompts_date_50c2d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.UniqueConstraint(fields=('topic', 'date'), name='uniq_topic_date'),
        ),
    ]
