# Generated by Django 5.2.17 on 2026-09-16 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=8)),
                ('body', models.TextField(blank=True, default='')),
                ('image_key', models.CharField(blank=True, default='', max_length=255)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reaction_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'indexes': [models.Index(fields=['prompt', 'status', '-published_at'], name='submissions_prompt__3c9500_idx'), models.Index(fields=['user', '-published_at'], name='submissions_user_id_0a156a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'prompt'), name='uniq_user_prompt')],
            },
        ),
    ]
